updated file ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,3 +17,12 @@ jobs:
 
     - name: Simple test
       run: echo "Pipeline is working!"
+
+    - name: Check HTML file
+  run: |
+    if [ -f index.html ]; then
+      echo "HTML file exists ✅"
+    else
+      echo "HTML file missing ❌"
+      exit 1
+    fi
